basePath: /v1
info:
  contact: {}
  description: Swagger API for Business X.
  termsOfService: http://swagger.io/terms/
  title: SM Swagger API
  version: "1.0"
paths: {}
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
