basePath: /v1
definitions:
  Account:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  Disposition:
    properties:
      createdBy:
        type: integer
      currency:
        type: string
      customerId:
        type: integer
      deliveryDate:
        type: string
      description:
        type: string
      requestType:
        enum:
        - order
        - quote
        type: string
    required:
    - createdBy
    - customerId
    - deliveryDate
    - description
    - requestType
    type: object
  DispositionResponse:
    properties:
      id:
        type: string
    type: object
  Dispositions:
    properties:
      dispositions:
        items:
          $ref: '#/definitions/Disposition'
        type: array
      limit:
        format: int64
        type: integer
      page:
        format: int64
        type: integer
      total:
        format: int64
        type: integer
    type: object
  Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for Business X.
  termsOfService: http://swagger.io/terms/
  title: SM Swagger API
  version: "1.0"
paths:
  /auth/login:
    post:
      operationId: login
      parameters:
      - description: Add login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Login'
      security:
      - ApiKeyAuth: []
      summary: Authenticate a user
  /auth/register:
    post:
      operationId: register
      parameters:
      - description: Add account details
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/Account'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
      summary: Register a user
  /disposition:
    get:
      operationId: get_dispositions
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit (max 100)
        in: query
        name: limit
        type: integer
      - description: pass nothing, 'order' or 'quote'
        in: query
        name: requestType
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Dispositions'
      security:
      - ApiKeyAuth: []
      summary: Get dispositions
    post:
      operationId: create_disposition
      parameters:
      - description: Add dispositions
        in: body
        name: disposition
        required: true
        schema:
          $ref: '#/definitions/Disposition'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/DispositionResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a disposition, an order or a quote
  /disposition/{id}:
    get:
      operationId: get_disposition
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Disposition'
      security:
      - ApiKeyAuth: []
      summary: Get disposition
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
